
namespace app.motionalarm.reporting
{

    sealed public class IntrusionReportContents
    {
        /// <summary>
        /// Represents the contents of the html (instrusion) report.
        /// </summary>
        public IntrusionReportContents()
        {
            this.softwareStamp = "Intrusion Detection Report by " + Globals.Application.applicationName;
            this.title = "Intrusion Detection Report";
            this.header = "This report was generated as a result of the " + Globals.Application.applicationName + " software having been " +
                "setup for scanning when motion was detected.  The image shows what the camera detected at the time the alarm was activated.";
            this.disclaimer = "NOTICE:" +
                "This is a report generated by the " + Globals.Application.applicationName + " software.  " +
                "By using this report, you understand that the results contained in it have no association with " +
                Globals.Application.companyName + ", it's employees, or any of it's affiliates and any proceedings (legal or otherwise)" +
                " and/or consequences that result in the usage of this report will not involve " + Globals.Application.companyName +
                ", employees, and affiliates in any way.";
            this.timeStamp = System.DateTime.Now;
            this.imagePath = null;
        }

        public string softwareStamp { get; set; }
        public string header { get; set; }
        public string title { get; set; }
        public System.DateTime timeStamp { get; set; }
        public string imagePath { get; set; }
        public string disclaimer { get; set; }
    }
}
